version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-code-agent-postgres
    environment:
      POSTGRES_DB: ai_code_agent
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup-postgres.sql:/docker-entrypoint-initdb.d/setup.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d ai_code_agent"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: